POST http://127.0.0.1:8000/find_communes/

[
    {
        "lat": 52.2297,
        "lon": 21.0122
    }, 
    {
        "lat": 52.2180,
        "lon": 21.0220
    },
    {
        "lat": 50.0591,
        "lon": 19.9400
    }
]